### ISSUE TITLE
BasicBlock中forward部分的疑问？

### ISSUE THREAD

**Issue by Gager-Git-life** [ohmydroid/reducenet#2]
<img width="490" alt="image" src="https://github.com/ohmydroid/reducenet/assets/47662641/722a117a-406d-4f11-8f3b-abbee5e6daa5">

第38行处的`out = self.bn1(self.conv1(out))`是否本意应该为`out = self.bn3(self.conv3(out))`
不然conv3，bn3没用到😂

**Comment by ohmydroid** [comment]
是的，我搞错了，谢谢提醒

**Comment by ohmydroid** [comment]
> 是的，我搞错了，谢谢提醒
